import { OPCODE, OPCODES } from "./opcodes";
import { ADDRESSING_MODES, ADDRESSING_MODE } from "./addressing_modes";

type Bytes = number;
type Cycles = number;
export type Instruction = [OPCODE, ADDRESSING_MODE, Bytes, Cycles];

interface InstructionMap {
    [opcode: number]: Instruction;
}

export const INSTRUCTIONS: InstructionMap = {
    /* Instruction ADC */
    0x69: [OPCODES.ADC, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0x65: [OPCODES.ADC, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x75: [OPCODES.ADC, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0x6D: [OPCODES.ADC, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0x7D: [OPCODES.ADC, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0x79: [OPCODES.ADC, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0x61: [OPCODES.ADC, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0x71: [OPCODES.ADC, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /* Instruction AND */
    0x29: [OPCODES.AND, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0x25: [OPCODES.AND, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x35: [OPCODES.AND, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0x2D: [OPCODES.AND, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0x3D: [OPCODES.AND, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0x39: [OPCODES.AND, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0x21: [OPCODES.AND, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0x31: [OPCODES.AND, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /** Instruction ASL */
    0x0A: [OPCODES.ASL_ACC, ADDRESSING_MODES.ACCUMULATOR, 1, 2],
    0x06: [OPCODES.ASL, ADDRESSING_MODES.ZERO_PAGE, 2, 5],
    0x16: [OPCODES.ASL, ADDRESSING_MODES.ZERO_PAGE_X, 2, 6],
    0x0E: [OPCODES.ASL, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    0x1E: [OPCODES.ASL, ADDRESSING_MODES.ABSOLUTE_X, 3, 7],
    /** Instruction BCC */
    0x90: [OPCODES.BCC, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BCS */
    0xB0: [OPCODES.BCS, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BEQ */
    0xF0: [OPCODES.BEQ, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BIT */
    0x24: [OPCODES.BIT, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x2C: [OPCODES.BIT, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    /** Instruction BMI */
    0x30: [OPCODES.BMI, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BNE */
    0xD0: [OPCODES.BNE, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BPL */
    0x10: [OPCODES.BPL, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BRK */
    0x00: [OPCODES.BRK, ADDRESSING_MODES.IMPLIED, 1, 7],
    /** Instruction BVC */
    0x50: [OPCODES.BVC, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BVS */
    0x70: [OPCODES.BVS, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction CLC */
    0x18: [OPCODES.CLC, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction CLD */
    0xD8: [OPCODES.CLD, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction CLI */
    0x58: [OPCODES.CLI, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction CLV */
    0xB8: [OPCODES.CLV, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction CMP */
    0xC9: [OPCODES.CMP, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xC5: [OPCODES.CMP, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xD5: [OPCODES.CMP, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0xCD: [OPCODES.CMP, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0xDD: [OPCODES.CMP, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0xD9: [OPCODES.CMP, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0xC1: [OPCODES.CMP, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0xD1: [OPCODES.CMP, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /** Instruction CPX */
    0xE0: [OPCODES.CPX, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xE4: [OPCODES.CPX, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xEC: [OPCODES.CPX, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    /** Instruction CPY */
    0xC0: [OPCODES.CPY, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xC4: [OPCODES.CPY, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xCC: [OPCODES.CPY, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    /** Instruction DEC */
    0xC6: [OPCODES.DEC, ADDRESSING_MODES.ZERO_PAGE, 2, 5],
    0xD6: [OPCODES.DEC, ADDRESSING_MODES.ZERO_PAGE_X, 2, 6],
    0xCE: [OPCODES.DEC, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    0xDE: [OPCODES.DEC, ADDRESSING_MODES.ABSOLUTE_X, 3, 7],
    /** Instruction DEX */
    0xCA: [OPCODES.DEX, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction DEY */
    0x88: [OPCODES.DEY, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction EOR */
    0x49: [OPCODES.EOR, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0x45: [OPCODES.EOR, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x55: [OPCODES.EOR, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0x4D: [OPCODES.EOR, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0x5D: [OPCODES.EOR, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0x59: [OPCODES.EOR, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0x41: [OPCODES.EOR, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0x51: [OPCODES.EOR, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /** Instruction INC */
    0xE6: [OPCODES.INC, ADDRESSING_MODES.ZERO_PAGE, 2, 5],
    0xF6: [OPCODES.INC, ADDRESSING_MODES.ZERO_PAGE_X, 2, 6],
    0xEE: [OPCODES.INC, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    0xFE: [OPCODES.INC, ADDRESSING_MODES.ABSOLUTE_X, 3, 7],
    /** Instruction INX */
    0xE8: [OPCODES.INX, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction INY */
    0xC8: [OPCODES.INY, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction JMP */
    0x4C: [OPCODES.JMP, ADDRESSING_MODES.ABSOLUTE, 3, 3],
    0x6C: [OPCODES.JMP, ADDRESSING_MODES.INDIRECT, 3, 5],
    /** Instruction JSR */
    0x20: [OPCODES.JSR, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    /** Instruction LDA */
    0xA9: [OPCODES.LDA, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xA5: [OPCODES.LDA, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xB5: [OPCODES.LDA, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0xAD: [OPCODES.LDA, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0xBD: [OPCODES.LDA, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0xB9: [OPCODES.LDA, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0xA1: [OPCODES.LDA, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0xB1: [OPCODES.LDA, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /** Instruction LDX */
    0xA2: [OPCODES.LDX, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xA6: [OPCODES.LDX, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xB6: [OPCODES.LDX, ADDRESSING_MODES.ZERO_PAGE_Y, 2, 4],
    0xAE: [OPCODES.LDX, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0xBE: [OPCODES.LDX, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    /** Instruction LDY */
    0xA0: [OPCODES.LDY, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xA4: [OPCODES.LDY, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xB4: [OPCODES.LDY, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0xAC: [OPCODES.LDY, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0xBC: [OPCODES.LDY, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    /** Instruction LSR */
    0x4A: [OPCODES.LSR_ACC, ADDRESSING_MODES.ACCUMULATOR, 1, 2],
    0x46: [OPCODES.LSR, ADDRESSING_MODES.ZERO_PAGE, 2, 5],
    0x56: [OPCODES.LSR, ADDRESSING_MODES.ZERO_PAGE_X, 2, 6],
    0x4E: [OPCODES.LSR, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    0x5E: [OPCODES.LSR, ADDRESSING_MODES.ABSOLUTE_X, 3, 7],
    /** Instruction NOP */
    0xEA: [OPCODES.NOP, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction ORA */
    0x09: [OPCODES.ORA, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0x05: [OPCODES.ORA, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x15: [OPCODES.ORA, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0x0D: [OPCODES.ORA, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0x1D: [OPCODES.ORA, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0x19: [OPCODES.ORA, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0x01: [OPCODES.ORA, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0x11: [OPCODES.ORA, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /** Instruction PHA */
    0x48: [OPCODES.PHA, ADDRESSING_MODES.IMPLIED, 1, 3],
    /** Instruction PHP */
    0x08: [OPCODES.PHP, ADDRESSING_MODES.IMPLIED, 1, 3],
    /** Instruction PLA */
    0x68: [OPCODES.PLA, ADDRESSING_MODES.IMPLIED, 1, 4],
    /** Instruction PLP */
    0x28: [OPCODES.PLP, ADDRESSING_MODES.IMPLIED, 1, 4],
    /** Instruction ROL */
    0x2A: [OPCODES.ROL_ACC, ADDRESSING_MODES.ACCUMULATOR, 1, 2],
    0x26: [OPCODES.ROL, ADDRESSING_MODES.ZERO_PAGE, 2, 5],
    0x36: [OPCODES.ROL, ADDRESSING_MODES.ZERO_PAGE_X, 2, 6],
    0x2E: [OPCODES.ROL, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    0x3E: [OPCODES.ROL, ADDRESSING_MODES.ABSOLUTE_X, 3, 7],
    /** Instruction ROR */
    0x6A: [OPCODES.ROR_ACC, ADDRESSING_MODES.ACCUMULATOR, 1, 2],
    0x66: [OPCODES.ROR, ADDRESSING_MODES.ZERO_PAGE, 2, 5],
    0x76: [OPCODES.ROR, ADDRESSING_MODES.ZERO_PAGE_X, 2, 6],
    0x6E: [OPCODES.ROR, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    0x7E: [OPCODES.ROR, ADDRESSING_MODES.ABSOLUTE_X, 3, 7],
    /** Instruction RTI */
    0x40: [OPCODES.RTI, ADDRESSING_MODES.IMPLIED, 1, 6],
    /** Instruction RTS */
    0x60: [OPCODES.RTS, ADDRESSING_MODES.IMPLIED, 1, 6],
    /** Instruction SBC */
    0xE9: [OPCODES.SBC, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xE5: [OPCODES.SBC, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xF5: [OPCODES.SBC, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0xED: [OPCODES.SBC, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0xFD: [OPCODES.SBC, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0xF9: [OPCODES.SBC, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0xE1: [OPCODES.SBC, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0xF1: [OPCODES.SBC, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /** Instruction SEC */
    0x38: [OPCODES.SEC, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction SED */
    0xF8: [OPCODES.SED, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction SEI */
    0x78: [OPCODES.SEI, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction STA */
    0x85: [OPCODES.STA, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x95: [OPCODES.STA, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0x8D: [OPCODES.STA, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0x9D: [OPCODES.STA, ADDRESSING_MODES.ABSOLUTE_X, 3, 5],
    0x99: [OPCODES.STA, ADDRESSING_MODES.ABSOLUTE_Y, 3, 5],
    0x81: [OPCODES.STA, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0x91: [OPCODES.STA, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 6],
    /** Instruction STX */
    0x86: [OPCODES.STX, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x96: [OPCODES.STX, ADDRESSING_MODES.ZERO_PAGE_Y, 2, 4],
    0x8E: [OPCODES.STX, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    /** Instruction STY */
    0x84: [OPCODES.STY, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x94: [OPCODES.STY, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0x8C: [OPCODES.STY, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    /** Instruction TAX */
    0xAA: [OPCODES.TAX, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction TAY */
    0xA8: [OPCODES.TAY, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction TSX */
    0xBA: [OPCODES.TSX, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction TXA */
    0x8A: [OPCODES.TXA, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction TXS */
    0x9A: [OPCODES.TXS, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction TYA */
    0x98: [OPCODES.TYA, ADDRESSING_MODES.IMPLIED, 1, 2],
}