import { INSTRUCTION, INSTRUCTIONS } from "./instructions";
import { ADDRESSING_MODES, ADDRESSING_MODE } from "./addressing_modes";

type Bytes = number;
type Cycles = number;

interface OpcodeMap {
    [opcode: number]: [INSTRUCTION, ADDRESSING_MODE, Bytes, Cycles];
}

export const OPCODES: OpcodeMap = {
    /* Instruction ADC */
    0x69: [INSTRUCTIONS.ADC, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0x65: [INSTRUCTIONS.ADC, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x75: [INSTRUCTIONS.ADC, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0x6D: [INSTRUCTIONS.ADC, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0x7D: [INSTRUCTIONS.ADC, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0x79: [INSTRUCTIONS.ADC, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0x61: [INSTRUCTIONS.ADC, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0x71: [INSTRUCTIONS.ADC, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /* Instruction AND */
    0x29: [INSTRUCTIONS.AND, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0x25: [INSTRUCTIONS.AND, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x35: [INSTRUCTIONS.AND, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0x2D: [INSTRUCTIONS.AND, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0x3D: [INSTRUCTIONS.AND, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0x39: [INSTRUCTIONS.AND, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0x21: [INSTRUCTIONS.AND, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0x31: [INSTRUCTIONS.AND, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /** Instruction ASL */
    0x0A: [INSTRUCTIONS.ASL_ACC, ADDRESSING_MODES.ACCUMULATOR, 1, 2],
    0x06: [INSTRUCTIONS.ASL, ADDRESSING_MODES.ZERO_PAGE, 2, 5],
    0x16: [INSTRUCTIONS.ASL, ADDRESSING_MODES.ZERO_PAGE_X, 2, 6],
    0x0E: [INSTRUCTIONS.ASL, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    0x1E: [INSTRUCTIONS.ASL, ADDRESSING_MODES.ABSOLUTE_X, 3, 7],
    /** Instruction BCC */
    0x90: [INSTRUCTIONS.BCC, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BCS */
    0xB0: [INSTRUCTIONS.BCS, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BEQ */
    0xF0: [INSTRUCTIONS.BEQ, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BIT */
    0x24: [INSTRUCTIONS.BIT, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x2C: [INSTRUCTIONS.BIT, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    /** Instruction BMI */
    0x30: [INSTRUCTIONS.BMI, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BNE */
    0xD0: [INSTRUCTIONS.BNE, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BPL */
    0x10: [INSTRUCTIONS.BPL, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BRK */
    0x00: [INSTRUCTIONS.BRK, ADDRESSING_MODES.IMPLIED, 1, 7],
    /** Instruction BVC */
    0x50: [INSTRUCTIONS.BVC, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction BVS */
    0x70: [INSTRUCTIONS.BVS, ADDRESSING_MODES.RELATIVE, 2, 2],
    /** Instruction CLC */
    0x18: [INSTRUCTIONS.CLC, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction CLD */
    0xD8: [INSTRUCTIONS.CLD, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction CLI */
    0x58: [INSTRUCTIONS.CLI, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction CLV */
    0xB8: [INSTRUCTIONS.CLV, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction CMP */
    0xC9: [INSTRUCTIONS.CMP, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xC5: [INSTRUCTIONS.CMP, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xD5: [INSTRUCTIONS.CMP, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0xCD: [INSTRUCTIONS.CMP, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0xDD: [INSTRUCTIONS.CMP, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0xD9: [INSTRUCTIONS.CMP, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0xC1: [INSTRUCTIONS.CMP, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0xD1: [INSTRUCTIONS.CMP, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /** Instruction CPX */
    0xE0: [INSTRUCTIONS.CPX, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xE4: [INSTRUCTIONS.CPX, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xEC: [INSTRUCTIONS.CPX, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    /** Instruction CPY */
    0xC0: [INSTRUCTIONS.CPY, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xC4: [INSTRUCTIONS.CPY, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xCC: [INSTRUCTIONS.CPY, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    /** Instruction DEC */
    0xC6: [INSTRUCTIONS.DEC, ADDRESSING_MODES.ZERO_PAGE, 2, 5],
    0xD6: [INSTRUCTIONS.DEC, ADDRESSING_MODES.ZERO_PAGE_X, 2, 6],
    0xCE: [INSTRUCTIONS.DEC, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    0xDE: [INSTRUCTIONS.DEC, ADDRESSING_MODES.ABSOLUTE_X, 3, 7],
    /** Instruction DEX */
    0xCA: [INSTRUCTIONS.DEX, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction DEY */
    0x88: [INSTRUCTIONS.DEY, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction EOR */
    0x49: [INSTRUCTIONS.EOR, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0x45: [INSTRUCTIONS.EOR, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x55: [INSTRUCTIONS.EOR, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0x4D: [INSTRUCTIONS.EOR, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0x5D: [INSTRUCTIONS.EOR, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0x59: [INSTRUCTIONS.EOR, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0x41: [INSTRUCTIONS.EOR, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0x51: [INSTRUCTIONS.EOR, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /** Instruction INC */
    0xE6: [INSTRUCTIONS.INC, ADDRESSING_MODES.ZERO_PAGE, 2, 5],
    0xF6: [INSTRUCTIONS.INC, ADDRESSING_MODES.ZERO_PAGE_X, 2, 6],
    0xEE: [INSTRUCTIONS.INC, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    0xFE: [INSTRUCTIONS.INC, ADDRESSING_MODES.ABSOLUTE_X, 3, 7],
    /** Instruction INX */
    0xE8: [INSTRUCTIONS.INX, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction INY */
    0xC8: [INSTRUCTIONS.INY, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction JMP */
    0x4C: [INSTRUCTIONS.JMP, ADDRESSING_MODES.ABSOLUTE, 3, 3],
    0x6C: [INSTRUCTIONS.JMP, ADDRESSING_MODES.INDIRECT, 3, 5],
    /** Instruction JSR */
    0x20: [INSTRUCTIONS.JSR, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    /** Instruction LDA */
    0xA9: [INSTRUCTIONS.LDA, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xA5: [INSTRUCTIONS.LDA, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xB5: [INSTRUCTIONS.LDA, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0xAD: [INSTRUCTIONS.LDA, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0xBD: [INSTRUCTIONS.LDA, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0xB9: [INSTRUCTIONS.LDA, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0xA1: [INSTRUCTIONS.LDA, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0xB1: [INSTRUCTIONS.LDA, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /** Instruction LDX */
    0xA2: [INSTRUCTIONS.LDX, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xA6: [INSTRUCTIONS.LDX, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xB6: [INSTRUCTIONS.LDX, ADDRESSING_MODES.ZERO_PAGE_Y, 2, 4],
    0xAE: [INSTRUCTIONS.LDX, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0xBE: [INSTRUCTIONS.LDX, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    /** Instruction LDY */
    0xA0: [INSTRUCTIONS.LDY, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xA4: [INSTRUCTIONS.LDY, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xB4: [INSTRUCTIONS.LDY, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0xAC: [INSTRUCTIONS.LDY, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0xBC: [INSTRUCTIONS.LDY, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    /** Instruction LSR */
    0x4A: [INSTRUCTIONS.LSR_ACC, ADDRESSING_MODES.ACCUMULATOR, 1, 2],
    0x46: [INSTRUCTIONS.LSR, ADDRESSING_MODES.ZERO_PAGE, 2, 5],
    0x56: [INSTRUCTIONS.LSR, ADDRESSING_MODES.ZERO_PAGE_X, 2, 6],
    0x4E: [INSTRUCTIONS.LSR, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    0x5E: [INSTRUCTIONS.LSR, ADDRESSING_MODES.ABSOLUTE_X, 3, 7],
    /** Instruction NOP */
    0xEA: [INSTRUCTIONS.NOP, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction ORA */
    0x09: [INSTRUCTIONS.ORA, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0x05: [INSTRUCTIONS.ORA, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x15: [INSTRUCTIONS.ORA, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0x0D: [INSTRUCTIONS.ORA, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0x1D: [INSTRUCTIONS.ORA, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0x19: [INSTRUCTIONS.ORA, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0x01: [INSTRUCTIONS.ORA, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0x11: [INSTRUCTIONS.ORA, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /** Instruction PHA */
    0x48: [INSTRUCTIONS.PHA, ADDRESSING_MODES.IMPLIED, 1, 3],
    /** Instruction PHP */
    0x08: [INSTRUCTIONS.PHP, ADDRESSING_MODES.IMPLIED, 1, 3],
    /** Instruction PLA */
    0x68: [INSTRUCTIONS.PLA, ADDRESSING_MODES.IMPLIED, 1, 4],
    /** Instruction PLP */
    0x28: [INSTRUCTIONS.PLP, ADDRESSING_MODES.IMPLIED, 1, 4],
    /** Instruction ROL */
    0x2A: [INSTRUCTIONS.ROL_ACC, ADDRESSING_MODES.ACCUMULATOR, 1, 2],
    0x26: [INSTRUCTIONS.ROL, ADDRESSING_MODES.ZERO_PAGE, 2, 5],
    0x36: [INSTRUCTIONS.ROL, ADDRESSING_MODES.ZERO_PAGE_X, 2, 6],
    0x2E: [INSTRUCTIONS.ROL, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    0x3E: [INSTRUCTIONS.ROL, ADDRESSING_MODES.ABSOLUTE_X, 3, 7],
    /** Instruction ROR */
    0x6A: [INSTRUCTIONS.ROR_ACC, ADDRESSING_MODES.ACCUMULATOR, 1, 2],
    0x66: [INSTRUCTIONS.ROR, ADDRESSING_MODES.ZERO_PAGE, 2, 5],
    0x76: [INSTRUCTIONS.ROR, ADDRESSING_MODES.ZERO_PAGE_X, 2, 6],
    0x6E: [INSTRUCTIONS.ROR, ADDRESSING_MODES.ABSOLUTE, 3, 6],
    0x7E: [INSTRUCTIONS.ROR, ADDRESSING_MODES.ABSOLUTE_X, 3, 7],
    /** Instruction RTI */
    0x40: [INSTRUCTIONS.RTI, ADDRESSING_MODES.IMPLIED, 1, 6],
    /** Instruction RTS */
    0x60: [INSTRUCTIONS.RTS, ADDRESSING_MODES.IMPLIED, 1, 6],
    /** Instruction SBC */
    0xE9: [INSTRUCTIONS.SBC, ADDRESSING_MODES.IMMEDIATE, 2, 2],
    0xE5: [INSTRUCTIONS.SBC, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0xF5: [INSTRUCTIONS.SBC, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0xED: [INSTRUCTIONS.SBC, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0xFD: [INSTRUCTIONS.SBC, ADDRESSING_MODES.ABSOLUTE_X, 3, 4],
    0xF9: [INSTRUCTIONS.SBC, ADDRESSING_MODES.ABSOLUTE_Y, 3, 4],
    0xE1: [INSTRUCTIONS.SBC, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0xF1: [INSTRUCTIONS.SBC, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 5],
    /** Instruction SEC */
    0x38: [INSTRUCTIONS.SEC, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction SED */
    0xF8: [INSTRUCTIONS.SED, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction SEI */
    0x78: [INSTRUCTIONS.SEI, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction STA */
    0x85: [INSTRUCTIONS.STA, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x95: [INSTRUCTIONS.STA, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0x8D: [INSTRUCTIONS.STA, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    0x9D: [INSTRUCTIONS.STA, ADDRESSING_MODES.ABSOLUTE_X, 3, 5],
    0x99: [INSTRUCTIONS.STA, ADDRESSING_MODES.ABSOLUTE_Y, 3, 5],
    0x81: [INSTRUCTIONS.STA, ADDRESSING_MODES.INDEXED_INDIRECT_X, 2, 6],
    0x91: [INSTRUCTIONS.STA, ADDRESSING_MODES.INDIRECT_INDEXED_Y, 2, 6],
    /** Instruction STX */
    0x86: [INSTRUCTIONS.STX, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x96: [INSTRUCTIONS.STX, ADDRESSING_MODES.ZERO_PAGE_Y, 2, 4],
    0x8E: [INSTRUCTIONS.STX, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    /** Instruction STY */
    0x84: [INSTRUCTIONS.STY, ADDRESSING_MODES.ZERO_PAGE, 2, 3],
    0x94: [INSTRUCTIONS.STY, ADDRESSING_MODES.ZERO_PAGE_X, 2, 4],
    0x8C: [INSTRUCTIONS.STY, ADDRESSING_MODES.ABSOLUTE, 3, 4],
    /** Instruction TAX */
    0xAA: [INSTRUCTIONS.TAX, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction TAY */
    0xA8: [INSTRUCTIONS.TAY, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction TSX */
    0xBA: [INSTRUCTIONS.TSX, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction TXA */
    0x8A: [INSTRUCTIONS.TXA, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction TXS */
    0x9A: [INSTRUCTIONS.TXS, ADDRESSING_MODES.IMPLIED, 1, 2],
    /** Instruction TYA */
    0x98: [INSTRUCTIONS.TYA, ADDRESSING_MODES.IMPLIED, 1, 2],
}